---
title: "Welcome to my blog"
date: 2020-06-09
---

title: "Welcome to my blog"
author: Lexi Roshkovan
email: lroshkovan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  My final AP Computer Science Principles project!

# social links
twitter_username: lexirosh # DO NOT include the @ character, or else the build will fail!
github_username:  lroshkovan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
